<?php

namespace App\Filament\Resources\TransactionResource\Pages;

use App\Filament\Resources\TransactionResource;
use App\Models\Transaction;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Concerns\InteractsWithInfolists;
use Filament\Infolists\Contracts\HasInfolists;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\Page;
use Filament\Support\Colors\Color;
use Filament\Support\Services\RelationshipJoiner;
use Filament\Tables;
use Filament\Tables\Concerns\InteractsWithTable;
use Filament\Tables\Contracts\HasTable;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Arr;

class TransactionDetails extends Page implements HasForms, HasInfolists, HasTable
{
    use InteractsWithForms, InteractsWithInfolists, InteractsWithTable;
    use TransactionResource\Pages\Traits\HasHeaderFunctions;

    protected static string $resource = TransactionResource::class;

    public Transaction $record;

    public bool $hasQuotation = false;

    protected function getHeaderWidgets(): array
    {
        return parent::getHeaderWidgets(); // TODO: Change the autogenerated stub
    }

    protected static string $view = 'filament.resources.transaction-resource.pages.transaction-details';

    public function mount(): void
    {
        $this->hasQuotation = $this->record->quotation()->exists();
    }

    protected function getTableQuery(): Builder|Relation|null
    {
        return $this->record->quotation->products();
    }

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->record($this->record)
            ->schema([
                Section::make('customer information')
                    ->collapsible()
                    ->collapsed()
                    ->schema([
                        TextEntry::make('id')
                            ->prefix('#')
                            ->extraAttributes([
                                'class' => 'font-bold',
                            ], true),
                        TextEntry::make('customer.latin_name')
                            ->badge(),
                    ])->columns(2),
            ]);
    }

    public function QuotationInfolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->record($this->record->quotation)
            ->schema([
                Section::make('quotation information')
                    ->collapsible()
                    ->collapsed()
                    ->schema([
                        TextEntry::make('cus_ref'),
                        TextEntry::make('attention'),
                    ]),
            ]);
    }

    public function invoiceInfolist(Infolist $infolist)
    {
        return $infolist
            ->record($this->record->invoice)
            ->schema([
                Section::make('invoice information')
                    ->collapsed()
                    ->collapsible()
                    ->schema([
                        TextEntry::make('id')
                            ->prefix('#'),
                    ]),
            ]);
    }

    public function table(Table $table): Table
    {

        return $table
            ->description('detail transaction')
            ->heading('transaction products')
            ->relationship(fn (): BelongsToMany => $this->record?->products())
            ->inverseRelationship('transactions')
            ->recordTitleAttribute('title')
            ->columns([
                Tables\Columns\TextColumn::make('title')
                    ->searchable(),
                Tables\Columns\ImageColumn::make('image'),
                Tables\Columns\TextColumn::make('price')
                    ->label('unit price')
                    ->color(Color::Green)
                    ->icon('heroicon-o-currency-dollar')
                    ->badge(),
                Tables\Columns\TextColumn::make('pivot.quantity')
                    ->label('quantity')
                    ->color(Color::Indigo)
                    ->icon('heroicon-o-circle-stack')
                    ->badge(),
                Tables\Columns\TextColumn::make('discount')
                    ->color(Color::Blue)
                    ->icon('heroicon-o-percent-badge')
                    ->badge()
                    ->default('0'),
                Tables\Columns\TextColumn::make('sold')
                    ->color(Color::Blue)
                    ->icon('heroicon-o-receipt-percent')
                    ->badge()
                    ->default('0'),
            ])
            ->filters([
                Tables\Filters\TrashedFilter::make(),
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
                Tables\Actions\AttachAction::make()
                    ->preloadRecordSelect()
                    ->action(function (array $arguments, array $data, Form $form, Table $table, Tables\Actions\AttachAction $action): void {
                        /** @var BelongsToMany $relationship */
                        $relationship = Relation::noConstraints(fn () => $table->getRelationship());

                        $relationshipQuery = app(RelationshipJoiner::class)->prepareQueryForNoConstraints($relationship);

                        $isMultiple = is_array($data['recordId']);

                        $record = $relationshipQuery
                            ->{$isMultiple ? 'whereIn' : 'where'}($relationship->getQualifiedRelatedKeyName(), $data['recordId'])
                            ->{$isMultiple ? 'get' : 'first'}();

                        if ($record instanceof Model) {
                            $action->record($record);
                        }

                        $action->process(function () use ($data, $record, $relationship) {
                            if ($record instanceof Model) {
                                $data['price'] = $record->price;
                            }

                            $relationship->attach(
                                $record,
                                Arr::only($data, $relationship->getPivotColumns()),
                            );
                        }, [
                            'relationship' => $relationship,
                        ]);

                        if ($arguments['another'] ?? false) {
                            $action->callAfter();
                            $action->sendSuccessNotification();

                            $action->record(null);

                            $form->fill();

                            $action->halt();
                        }

                        $action->success();
                    }),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DetachAction::make(),
                Tables\Actions\ForceDeleteAction::make(),
                Tables\Actions\RestoreAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DetachBulkAction::make(),
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\RestoreBulkAction::make(),
                    Tables\Actions\ForceDeleteBulkAction::make(),
                ]),
            ])
            ->modifyQueryUsing(fn (Builder $query) => $query->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]));
    }

    protected function getHeaderActions(): array
    {
        if ($this->record->quotation()->exists()) {
            return [
                $this->getEditQuotationAction(),
                $this->savePdfAction(),
                $this->createInvoiceFromQuotationAction(),
            ];
        }

        return [
            $this->createQuotationAction(),
        ];
    }

    protected function getFooterWidgets(): array
    {
        return [

        ];
    }
}
